# frozen_string_literal: true

module Constants
  PLACE = 'PLACE'
  PLACE_OBSTACLE = 'PLACE_OBSTACLE'
  MOVE = 'MOVE'
  LEFT = 'LEFT'
  RIGHT = 'RIGHT'
  REPORT = 'REPORT'
  FIND_PATH = 'FIND_PATH'
  COMMANDS = [PLACE, MOVE, LEFT, RIGHT, REPORT, PLACE_OBSTACLE, FIND_PATH].freeze
end
